name: pastey

services:
  pastey:
    image: cesura/pastey:0.5.1-slim
    user: nobody:nogroup
    networks:
      - default
    env_file:
      - ./app.env
    volumes:
      - pastey:/app/data

networks:
  default:

volumes:
  pastey:

