services:
  pastey:
    image: cesura/pastey:0.5.1-slim
    user: nobody:nogroup
    networks:
      - web
    env_file:
      - ./app.env
    volumes:
      - ./data:/app/data

networks:
  web:
    external: true

