services:
  app:
    container_name: pastey
    image: cesura/pastey:0.5.1-slim
    restart: unless-stopped
    user: nobody:nogroup
    networks:
      - default
    env_file:
      - ./app.env
    volumes:
      - ./data:/app/data
      - ./fixes/routes.py:/app/pastey/routes.py:ro

networks:
  default:
    name: web
    external: true

